---
strategy: webhook
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: ''
polling_headers: ''
polling_body: ''
id: 158676
custom_fields:
- keyname: author_bio
  name: About This Plugin
  field_type: author_bio
  description: Watch results of recent Proxmox backups
  github_url: https://github.com/MartinBelko/TRMNL-Plugin-Proxmox-Backups
name: Proxmox Test
refresh_interval: 1440
